#!/bin/bash
set -euo pipefail

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname postgres <<EOSQL
  CREATE USER ${AIRFLOW_DB_USER} WITH PASSWORD '${AIRFLOW_DB_PASSWORD}';
  CREATE DATABASE ${AIRFLOW_DB} OWNER ${AIRFLOW_DB_USER};
  CREATE USER ${WAREHOUSE_DB_USER} WITH PASSWORD '${WAREHOUSE_DB_PASSWORD}';
  CREATE DATABASE ${WAREHOUSE_DB} OWNER ${WAREHOUSE_DB_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "${WAREHOUSE_DB}" <<EOSQL
  CREATE SCHEMA IF NOT EXISTS staging      AUTHORIZATION ${WAREHOUSE_DB_USER};
  CREATE SCHEMA IF NOT EXISTS intermediate AUTHORIZATION ${WAREHOUSE_DB_USER};
  CREATE SCHEMA IF NOT EXISTS marts        AUTHORIZATION ${WAREHOUSE_DB_USER};
  CREATE SCHEMA IF NOT EXISTS snapshots    AUTHORIZATION ${WAREHOUSE_DB_USER};
  CREATE SCHEMA IF NOT EXISTS monitoring   AUTHORIZATION ${WAREHOUSE_DB_USER};
EOSQL